### ISSUE TITLE
verbose descriptions of GUI elements

### ISSUE THREAD

**Issue by florian-grond** [BIAPT/EEGsonic#4]
If the MATLAB GUI allows adding mouse over popup, it would be great to have more verbose information about the parameters that can be set in the GUI.
If one parameter is windowsize than it could say for instance windowsize of ...
and it could also provide info for reasonable default values as well as minimum and maximum values, should they exist, and the limiting factors to consider when adjusting these values.

I understand that not all this can go into the GUI but maybe there is the possibility to add an info popup

**Comment by yacineMahdid** [comment]
Great Idea, I'll look in the documentation if there is a way of doing this!

**Comment by yacineMahdid** [comment]
Made the documentation viewer we just need to fill up the text files
