### ISSUE TITLE
Issue with converting and running .set files

### ISSUE THREAD

**Issue by jamiecwebber** [BIAPT/EEGsonic#59]
<img width="574" alt="Screen Shot 2019-12-05 at 11 01 52 AM" src="https://user-images.githubusercontent.com/38967452/70252680-d4e73980-174f-11ea-8c15-de8c27215324.png">

I selected Jamie_listen_music.set and selected an output folder

<img width="881" alt="Screen Shot 2019-12-05 at 11 05 07 AM" src="https://user-images.githubusercontent.com/38967452/70252806-0d871300-1750-11ea-9215-3353780b4ef8.png">

I select the new folder as the replay folder

<img width="895" alt="Screen Shot 2019-12-05 at 11 06 06 AM" src="https://user-images.githubusercontent.com/38967452/70252932-3c9d8480-1750-11ea-88cc-c3854dd12b59.png">

It doesn't pre-populate the fields with defaults like it normally does. (?) This error comes when I check the Topographic Distribution.

<img width="685" alt="Screen Shot 2019-12-05 at 11 07 36 AM" src="https://user-images.githubusercontent.com/38967452/70253052-7b333f00-1750-11ea-8653-1a1f894a602d.png">

PAC is showing NaN values

<img width="870" alt="Screen Shot 2019-12-05 at 11 09 03 AM" src="https://user-images.githubusercontent.com/38967452/70253080-88e8c480-1750-11ea-998a-99d2dc3c2718.png">

If I select the input channels listed on Nov 14 in the Slack channel for wPLI, I get "error using Zeroes"

**Comment by yacineMahdid** [comment]
This is caused by conflict with NeuroAlgo, just make sure that EEGsonic is the only thing in the path. In doubt just exit Matlab and reopen it.
